# Generated by Django 4.1.3 on 2022-11-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemRecords',
        ),
        migrations.RemoveField(
            model_name='createinvoice',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
        migrations.AddField(
            model_name='createinvoice',
            name='itemname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='createinvoice',
            name='sheduledate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sendemails',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='createinvoice',
            name='brandname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='createinvoice',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createinvoice',
            name='invoiceno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='createinvoice',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
