# Generated by Django 4.1.3 on 2022-11-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_itemrecords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendInvoicemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromemial', models.EmailField(max_length=254)),
                ('tomail', models.EmailField(max_length=254)),
                ('shedultime', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
