# Generated by Django 4.1.3 on 2022-11-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sendinvoicemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendinvoicemail',
            name='shedultime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
