# Generated by Django 4.1.3 on 2022-11-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_sendinvoicemail_shedultime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsDetais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='createinvoice',
            name='itemname',
        ),
        migrations.RemoveField(
            model_name='createinvoice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='createinvoice',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='createinvoice',
            name='total',
        ),
    ]
