# Generated by Django 4.1.3 on 2022-11-22 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_itemsdetais_remove_createinvoice_itemname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createinvoice',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Invoice_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
