# Generated by Django 4.1.3 on 2022-11-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_createinvoice_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsdetais',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemsdetais',
            name='qty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemsdetais',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
