# Generated by Django 4.1.3 on 2022-11-22 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_itemsdetais_price_alter_itemsdetais_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createinvoice',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Invoice_item', to='app.itemsdetais'),
        ),
    ]
