# Generated by Django 4.1.3 on 2022-11-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_createinvoice_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendinvoicemail',
            name='uploadfile',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='files/'),
        ),
    ]
