# Generated by Django 4.1.3 on 2022-11-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_sendinvoicemail_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendinvoicemail',
            name='uploadfile',
            field=models.FileField(default=None, null=True, upload_to='files/'),
        ),
    ]
