# Generated by Django 4.1.3 on 2022-11-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_sendinvoicemail_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendinvoicemail',
            name='uploadfile',
            field=models.FileField(default=None, null=True, upload_to='media'),
        ),
    ]
