# Generated by Django 4.1.3 on 2022-11-24 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_sendinvoicemail_uploadfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createinvoice',
            name='item',
        ),
        migrations.AddField(
            model_name='itemsdetais',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CreateInvoice_item', to='app.createinvoice'),
        ),
    ]
