# Generated by Django 4.1.3 on 2022-11-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_createinvoice_item_itemsdetais_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createinvoice',
            name='date',
        ),
    ]
