# Generated by Django 4.1.3 on 2022-11-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_createinvoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createinvoice',
            name='subtotal',
        ),
    ]
