# Generated by Django 4.1.3 on 2022-11-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_createinvoice_reciver_usermail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createinvoice',
            name='uploadfile',
            field=models.FileField(default=None, null=True, upload_to='create'),
        ),
    ]
