# Generated by Django 4.1.3 on 2022-11-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_createinvoice_uploadfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createinvoice',
            name='uploadfile',
        ),
        migrations.AddField(
            model_name='createinvoice',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
